# Generated by Django 2.0.2 on 2018-04-13 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Linguagem')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('html_url', models.CharField(max_length=256, verbose_name='URL')),
                ('stargazers_count', models.IntegerField(verbose_name='Stars')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='github.ProgrammingLanguage', verbose_name='Linguagem')),
            ],
        ),
    ]
