# Generated by Django 2.0.2 on 2018-04-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='stargazers_count',
            field=models.IntegerField(default=None, verbose_name='Stars'),
            preserve_default=False,
        ),
    ]
