# Generated by Django 2.0.2 on 2018-04-13 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_auto_20180412_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='github.ProgrammingLanguage', verbose_name='Linguagem'),
        ),
    ]
